数据库模块
EasyCode-Platform/EasyCode_Backend pull request #3
Opened 2023-09-20 10:12 UTC by 1732897325

让cto见笑了

2023-09-20 12:13 UTC, Chiichen requested changes
主要问题一个是层次问题，一般来说应该要有的是 Router、Handler（简单的需求可以不用）、Service、Model层，现在基本上是 all in one，而且很多操作都没有做Restful接口，这样是不合适的。要给出Restful接口然后用postman做接口测试才行
第二是可能你一开始应该是想做成一个包哈哈哈，没有做主程序，但是，是要做的。
第三是一些网络配置好像没有做，比如跨域之类的

2023-09-20 12:13 UTC, chiichen commented on database-backend/.DS_Store
这是什么文件，如果是编译或者运行时产生的要 ignore

2023-09-20 12:13 UTC, chiichen commented on database-backend/api/db/mysql_action.go
> +type User struct {
entity 应该单独拿出来，不能放在db这个包下面

2023-09-20 12:13 UTC, chiichen commented on database-backend/db_test/main_test.go
> +func TestMain(m *testing.M) {
把它放到cmd目录下，改成main函数。

2023-09-20 12:13 UTC, chiichen commented on database-backend/db_test/mysql_test.go
> +	_, err := db2.ConnectDB(username, password, host, port, database)
这个是什么包，用 gorm 是不是好一点

2023-09-20 12:13 UTC, chiichen commented on database-backend/api/db/mongo_action.go
层次结构不太对，这个代码不应该放在api目录下，api应该存放类似于MVC模型里的controller层或者handler层的代码，现在这部分代码应该属于service层，应该放在例如internal/repository这种目录下。

2023-09-20 12:13 UTC, chiichen commented on database-backend/db_test/gin_test.go
Gin引擎的初始化写到主程序main的init部分里。然后路由规则和分发要写在/router目录下，用对应功能的router去做

2023-09-20 12:13 UTC, chiichen commented on database-backend/db_test/main_test.go
这个地方直接写成主程序main就可以了，不用当成一个包来写

2023-09-20 12:13 UTC, chiichen commented on database-backend/maintest
跟之前的一样的，如果是编译或者运行时产生的包要 ignore 掉

2023-09-20 12:13 UTC, chiichen commented on database-backend/data/data_handle.go
如果你是为了解析config的话我觉得用"github.com/caarlos0/env"这个库会好很多，你都不用写这些工具类，不用匹配路径也不用去定义这些名字。直接在UserName   string后面加一个json字符串就能直接解析了

2023-09-20 12:13 UTC, chiichen commented on database-backend/api/db/redis_cache.go
> +	rdb := redis.NewClient(&redis.Options{
这里其实最好把所有配置写在一起(就像spring一样)，然后再读这个 all in one 的配置，不然后续改动会比较麻烦

2023-09-20 12:36 UTC, 1732897325 commented
> 主要问题一个是层次问题，一般来说应该要有的是 Router、Handler（简单的需求可以不用）、Service、Model层，现在基本上是 all in one，而且很多操作都没有做Restful接口，这样是不合适的。要给出Restful接口然后用postman做接口测试才行 第二是可能你一开始应该是想做成一个包哈哈哈，没有做主程序，但是，是要做。 第三是一些网络配置好像没有做，比如跨域之类的

2023-10-19 08:16 UTC, Chiichen requested changes

2023-10-19 08:16 UTC, chiichen commented on database-backend/config/data_handle.go
> -import "awesomeProject/tools"
这个 awesomeProject 应该改成上游仓库的名字好一点吧，不然后面 clone 上游仓库的话这个路径就错了

2023-10-19 08:16 UTC, Chiichen commented on database-backend/models/component.go
>  	componentData []ComponentData
这里你是打算怎么存储组件的信息的，我总感觉这个数组有点怪怪的

2023-12-04 09:40 UTC, closed without merging